### ISSUE TITLE
Configurar o pom.xml seguindo o modelo dado em classe

### ISSUE THREAD

**Issue by danielbastos11** [danielbastos11/Corp2016.1#4]
Configurar o pom.xml do projeto de acordo com o modelo do projeto conta, incluindo:

- equipe de desenvolvedores, endereço SCM
- os relatórios pmd, cpd, jdepend, findbugs, javadoc, xref
- profile para verificar no build o pmd, cpd, jdepend e findbugs

**Comment by danielbastos11** [comment]
Não consegui marcar mais de uma pessoa pra fazer, mas fica @Bonei e @nicaciobarbalho nessa tarefa, beleza?

**Comment by Bonei** [comment]
Eu fiz:

 - equipe de desenvolvedores, endereço SCM (Ficou faltando as confis de acordo com o projeto CONTA, porém a estrutura tá montada)
 - os relatórios pmd, cpd, jdepend, findbugs, javadoc, xref 

Ficou faltando os profiles, no caso, seria para Nicácio, como ele não apareceu e como eu também não soube fazer, pediremos auxílio ao professor.
